import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useL } from '../i18n';
import { Contours, Ring, Num, useReveal } from '../ui';
import { PriceCards } from './Public';

const Arr = () => <span className="arr"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M13 6l6 6-6 6" /></svg></span>;

function Faq({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return <div className={`it ${open ? 'open' : ''}`}><button onClick={() => setOpen(!open)} aria-expanded={open}>{q}<i>+</i></button><div className="bd"><div><p>{a}</p></div></div></div>;
}

export default function Landing() {
  const { L } = useL(), loc = useLocation(), hero = useRef<HTMLElement>(null), [tab, setTab] = useState(0);
  useReveal();
  useEffect(() => { if (loc.hash === '#how') setTimeout(() => document.getElementById('how')?.scrollIntoView({ behavior: 'smooth' }), 60); }, [loc]);
  const move = (e: React.MouseEvent) => { const r = hero.current!.getBoundingClientRect(); hero.current!.style.setProperty('--mx', String(((e.clientX - r.left) / r.width - 0.5) * 2)); hero.current!.style.setProperty('--my', String(((e.clientY - r.top) / r.height - 0.5) * 2)); };
  const docs = ['Sale deed', 'Patta', 'Chitta', 'Encumbrance certificate', 'Parent deed', 'FMB sketch', 'Layout approval', 'Tax receipt', 'Broker claims', 'Map data'];
  const tabs: { t: string; s: string; rows: [string, string, string, '' | 'a' | 'r'][]; out: string }[] = [
    { t: L('Sale deed and patta', 'விற்பனை பத்திரம் & பட்டா'), s: L('Same owner, survey, extent?', 'ஒரே உரிமையாளர், சர்வே, பரப்பு?'), rows: [[L('Seller / holder', 'விற்பவர் / பட்டாதாரர்'), 'Ravi Kumar', 'Ravi Kumar', ''], [L('Survey number', 'சர்வே எண்'), '123/4A', '123/4A', ''], [L('Extent (sq.ft)', 'பரப்பு (ச.அடி)'), '2,400', '2,100', 'r']], out: L('Extent differs by 300 sq.ft. Verify with a surveyor before the advance.', 'பரப்பு 300 ச.அடி வேறுபடுகிறது. முன்பணத்துக்கு முன் சர்வேயரிடம் சரிபார்க்கவும்.') },
    { t: L('Encumbrance certificate', 'வில்லங்க சான்று'), s: L('Any open charge?', 'திறந்த பாரம் உள்ளதா?'), rows: [['2016', L('Mortgage · Doc 977', 'அடமானம் · ஆவணம் 977'), L('Open', 'திறந்தது'), 'r'], ['2019', L('Sale deed · Doc 1842', 'விற்பனை பத்திரம் · 1842'), L('Clear', 'தெளிவு'), ''], ['2021', L('Part release · Doc 2310', 'பகுதி விடுவிப்பு · 2310'), L('Partial', 'பகுதி'), 'a']], out: L('One charge is still open. Ask for the discharge proof.', 'ஒரு பாரம் இன்னும் திறந்துள்ளது. விடுவிப்பு ஆதாரம் கேளுங்கள்.') },
    { t: L('Parent deed', 'தாய்ப் பத்திரம்'), s: L('Did the seller truly receive it?', 'விற்பவருக்கு உண்மையில் வந்ததா?'), rows: [[L('Parent deed buyer', 'தாய்ப் பத்திர வாங்குபவர்'), 'Ravi Kumar', '905/1998', ''], [L('Sale deed seller', 'பத்திர விற்பவர்'), 'Ravi Kumar', '1842/2024', ''], [L('Patta holder', 'பட்டாதாரர்'), 'Ravi Kumar', '2023', '']], out: L('The chain holds: parent deed, sale deed and patta agree on the owner.', 'சங்கிலி சரி: தாய்ப் பத்திரம், விற்பனை பத்திரம், பட்டா ஒரே உரிமையாளரை காட்டுகின்றன.') },
    { t: L('Layout approval', 'லேஅவுட் அனுமதி'), s: L('Is the plot inside it?', 'மனை அதற்குள் உள்ளதா?'), rows: [[L('Reference', 'எண்'), 'LP/2019/118', 'DTCP', ''], [L('Survey covered', 'உள்ளடக்கிய சர்வே'), '123/4A', L('Matches', 'பொருந்தும்'), ''], [L('Official confirmation', 'அதிகாரப்பூர்வ உறுதி'), '–', L('Not yet', 'இல்லை'), 'a']], out: L('A reference in the seller’s own paper is not official. Ask the authority to confirm.', 'விற்பவரின் ஆவணத்தில் உள்ள எண் அதிகாரப்பூர்வம் அல்ல. அதிகாரியிடம் உறுதி செய்க.') },
    { t: L('Map and broker claims', 'வரைபடம் & தரகர் கூற்றுகள்'), s: L('Is “1 km” really 1 km?', '“1 கி.மீ” உண்மையா?'), rows: [[L('Broker says', 'தரகர்'), L('Hospital within 1 km', '1 கி.மீ-ல் மருத்துவமனை'), '', ''], [L('Nearest, straight line', 'அருகில், நேர்கோடு'), '1.7 km', 'OSM', ''], [L('Verdict', 'முடிவு'), L('Not supported', 'உறுதியில்லை'), '', 'r']], out: L('A road is never shorter than a straight line, so this claim cannot be true.', 'சாலை நேர்கோட்டை விட குறைவாகாது; எனவே இந்த கூற்று உண்மையாக இருக்க முடியாது.') },
  ];
  const T = tabs[tab];
  const faq = [
    [L('Can you tell me if the land is legal?', 'நிலம் சட்டப்படி சரியா என்று சொல்ல முடியுமா?'), L('No, and we will not pretend to. We tell you what the documents and data show, where they disagree, and what nobody has checked. For title and boundaries you still need an advocate and a surveyor, and you can request both from inside the app.', 'இல்லை, அப்படி நடிக்கவும் மாட்டோம். ஆவணங்களும் தரவும் என்ன காட்டுகின்றன, எங்கு முரண்படுகின்றன, எதை யாரும் சரிபார்க்கவில்லை என்று சொல்கிறோம். உரிமை, எல்லைக்கு வழக்கறிஞர், சர்வேயர் தேவை; செயலியிலேயே கோரலாம்.')],
    [L('Do you connect to government portals?', 'அரசு தளங்களுடன் இணைக்கிறீர்களா?'), L('Not yet. Today the audit runs on the documents you upload plus open map data. Government sources show as “not verified” in your report. We will add them only through authorised access.', 'இன்னும் இல்லை. இப்போது நீங்கள் பதிவேற்றும் ஆவணங்கள், திறந்த வரைபட தரவில் தணிக்கை நடக்கிறது. அரசு மூலங்கள் “சரிபார்க்கப்படவில்லை” என காட்டப்படும்; அங்கீகரிக்கப்பட்ட அணுகல் மூலமே சேர்ப்போம்.')],
    [L('What does the score mean?', 'மதிப்பெண் என்ன அர்த்தம்?'), L('It covers only what was checked, and it always comes with an evidence coverage figure. A critical finding caps the score regardless.', 'சரிபார்த்தவற்றை மட்டுமே உள்ளடக்கும்; எப்போதும் ஆதார வரம்புடன் வரும். மிக முக்கிய முடிவு இருந்தால் மதிப்பெண் உச்சவரம்புக்குள் இருக்கும்.')],
    [L('Are my documents safe?', 'என் ஆவணங்கள் பாதுகாப்பானவையா?'), L('Your documents are used to produce your report. You can delete your account and every case from Settings at any time.', 'ஆவணங்கள் உங்கள் அறிக்கைக்காக மட்டுமே. அமைப்புகளில் எப்போது வேண்டுமானாலும் கணக்கையும் அனைத்து வழக்குகளையும் நீக்கலாம்.')],
  ];
  const steps = [[L('Add the property', 'நிலத்தை சேர்'), L('District, survey number, extent and a pin on the map.', 'மாவட்டம், சர்வே எண், பரப்பு, வரைபடத்தில் பின்.')], [L('Upload and confirm', 'பதிவேற்றி உறுதி செய்'), L('We read the values. You confirm or edit each one.', 'மதிப்புகளை படிக்கிறோம். நீங்கள் உறுதி / திருத்துங்கள்.')], [L('We cross-check', 'நாங்கள் ஒப்பிடுகிறோம்'), L('Documents against each other, claims against the map.', 'ஆவணங்கள் ஒன்றோடொன்று; கூற்றுகள் வரைபடத்துடன்.')], [L('Read the report', 'அறிக்கையை படி'), L('Findings with evidence and questions for the seller.', 'ஆதாரத்துடன் முடிவுகள், விற்பவருக்கான கேள்விகள்.')]];
  return <div className="lp">
    <section className="hero-lp" ref={hero} onMouseMove={move}>
      <Contours />
      <div className="pf" style={{ left: 'calc(50% - 790px)', top: 130, ['--k' as string]: 14 }}><div className="fcard"><h4>{L('Extent check', 'பரப்பு சோதனை')}<span className="mono">{L('sample', 'மாதிரி')}</span></h4><div className="r"><span className="mu">{L('Sale deed', 'பத்திரம்')}</span><b>2,400 sq.ft</b></div><div className="r"><span className="mu">{L('Patta', 'பட்டா')}</span><b>2,100 sq.ft</b></div><div className="r"><span className="mono" style={{ color: '#B63A3A', background: '#F9E5E3', padding: '2px 8px', borderRadius: 8 }}>-300 sq.ft · 12.5%</span></div></div></div>
      <div className="pf" style={{ left: 'calc(50% - 740px)', top: 370, ['--k' as string]: -10 }}><div className="fcard" style={{ animationDelay: '1.2s' }}><h4>{L('Ownership chain', 'உரிமை சங்கிலி')}<span className="mono">4 / 5</span></h4>{[[L('Parent deed → seller', 'தாய்ப் பத்திரம் → விற்பவர்'), 1], [L('Seller = patta holder', 'விற்பவர் = பட்டாதாரர்'), 1], [L('EC: no open charge', 'EC: திறந்த பாரம் இல்லை'), 1], [L('Approval confirmed', 'அனுமதி உறுதி'), 0]].map(x => <div className="r" key={String(x[0])}><span>{x[0]}</span><b style={{ color: x[1] ? '#0E7A55' : '#9A6A0C' }}>{x[1] ? '✓' : '○'}</b></div>)}</div></div>
      <div className="pf" style={{ right: 'calc(50% - 790px)', top: 110, ['--k' as string]: -14 }}><div className="fcard" style={{ animationDelay: '.6s' }}><h4>{L('Evidence ledger', 'ஆதார பதிவு')}<span className="mono">{L('sample', 'மாதிரி')}</span></h4>{[['Sale deed · p.4', '96%'], ['Patta · p.2', '91%'], ['OpenStreetMap', 'live']].map(x => <div className="r" key={x[0]}><span className="mono">{x[0]}</span><b>{x[1]}</b></div>)}<div className="mono" style={{ color: '#9A6A0C', marginTop: 4 }}>{L('Road access: not verified', 'சாலை அணுகல்: சரிபார்க்கவில்லை')}</div></div></div>
      <div className="pf" style={{ right: 'calc(50% - 740px)', top: 350, ['--k' as string]: 10 }}><div className="fcard" style={{ animationDelay: '1.8s' }}><h4>{L('Readiness', 'தயார்நிலை')}<span className="mono">{L('sample', 'மாதிரி')}</span></h4><div className="row"><Ring v={82} size={78} /><div><b>{L('Verify first', 'முதலில் சரிபார்')}</b><div className="mu sm">{L('Coverage', 'வரம்பு')} 45%</div></div></div></div></div>
      <div className="pub-in" style={{ position: 'relative' }}>
        <span className="pillt rv"><i />{L('Land due diligence for Tamil Nadu', 'தமிழ்நாட்டிற்கான நில சரிபார்ப்பு')}</span>
        <h1 className="rv" style={{ transitionDelay: '.08s' }}>{L('Check the land ', 'நிலத்தை ')}<em>{L('before', 'முன்பே')}</em>{L(' you pay for it.', ' சரிபாருங்கள், பணம் கொடுக்கும் முன்.')}</h1>
        <p className="lead rv" style={{ transitionDelay: '.16s' }}>{L('Upload the sale deed, patta and encumbrance certificate. LandAudit compares them with each other and with map data, then tells you what matches, what does not, and what nobody has checked yet.', 'விற்பனை பத்திரம், பட்டா, வில்லங்க சான்றை பதிவேற்றுங்கள். அவற்றை ஒன்றோடொன்றும் வரைபட தரவுடனும் ஒப்பிட்டு, எது பொருந்துகிறது, எது இல்லை, எதை இன்னும் யாரும் சரிபார்க்கவில்லை என்று சொல்கிறோம்.')}</p>
        <div className="row wrap rv" style={{ justifyContent: 'center', transitionDelay: '.24s' }}><Link className="btn lg" to="/register">{L('Start free', 'இலவசமாக தொடங்கு')}<Arr /></Link><Link className="btn o lg" to="/sample">{L('See a sample report', 'மாதிரி அறிக்கையை பார்')}<Arr /></Link></div>
        <div className="row wrap rv" style={{ justifyContent: 'center', marginTop: 26, gap: 10, transitionDelay: '.32s' }}>{[L('First audit free', 'முதல் தணிக்கை இலவசம்'), L('English and தமிழ்', 'ஆங்கிலம் & தமிழ்'), L('Every finding shows its evidence', 'ஒவ்வொரு முடிவுக்கும் ஆதாரம்')].map(x => <span key={x} className="tag n" style={{ background: '#fff', padding: '5px 14px', fontWeight: 500 }}>{x}</span>)}</div>
      </div>
    </section>

    <div className="marq" aria-hidden="true"><div>{[...docs, ...docs].map((d, i) => <span key={i}>{d}</span>)}</div></div>

    <section className="sec" id="how"><div className="pub-in">
      <h2 className="rv">{L('From documents to a decision in four steps', 'ஆவணங்களிலிருந்து முடிவு வரை, நான்கு படிகளில்')}</h2>
      <p className="lead rv">{L('You stay in control. Every value we read is shown with its page and confidence, and you confirm it before it counts.', 'கட்டுப்பாடு உங்களிடமே. படிக்கும் ஒவ்வொரு மதிப்பும் பக்கம், நம்பகத்தன்மையுடன் காட்டப்படும்; நீங்கள் உறுதி செய்த பின்னரே கணக்கில் வரும்.')}</p>
      <div className="hstep">{steps.map((x, i) => <div className="st rv" key={i} style={{ transitionDelay: `${i * 0.1}s` }}><b>0{i + 1}</b><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div>
    </div></section>

    <section className="sec" style={{ paddingTop: 20 }}><div className="pub-in">
      <h2 className="rv">{L('What we check, document by document', 'ஆவணம் ஆவணமாக நாங்கள் சரிபார்ப்பவை')}</h2>
      <p className="lead rv">{L('Pick a document to see the check we run on it.', 'ஒரு ஆவணத்தை தேர்ந்து அதன் மீது நாங்கள் செய்யும் சோதனையை பாருங்கள்.')}</p>
      <div className="chk rv"><div className="lst">{tabs.map((x, i) => <button key={i} className={tab === i ? 'on' : ''} onClick={() => setTab(i)}>{x.t}<small>{x.s}</small></button>)}</div>
        <div className="view" key={tab}><table className="tbl" style={{ marginBottom: 14 }}><tbody>{T.rows.map((r, i) => <tr key={i}><td style={{ paddingLeft: 0 }} className="mu">{r[0]}</td><td><b>{r[1]}</b></td><td className="mono">{r[2]}</td><td style={{ textAlign: 'right' }}>{r[3] && <span className={`tag ${r[3]}`}>{r[3] === 'r' ? L('Check', 'சரிபார்') : L('Review', 'ஆய்வு')}</span>}{!r[3] && <span className="tag">✓</span>}</td></tr>)}</tbody></table>
          <div style={{ background: 'var(--bg)', borderRadius: 14, padding: '14px 16px' }}><b>{L('What you read', 'நீங்கள் படிப்பது')}: </b>{T.out}</div></div></div>
    </div></section>

    <section className="sec" style={{ paddingTop: 20 }}><div className="pub-in g c2" style={{ alignItems: 'center', gap: 56 }}>
      <div className="rv"><h2>{L('A score that admits what it did not check', 'சரிபார்க்காததை ஒப்புக்கொள்ளும் மதிப்பெண்')}</h2><p className="lead">{L('80 out of 100 on 45% coverage is a very different thing from 80 on 90%. Every report shows both numbers, and a critical finding caps the score.', '45% வரம்பில் 80 என்பது 90% வரம்பில் 80-க்கு சமமல்ல. ஒவ்வொரு அறிக்கையும் இரண்டையும் காட்டும்; மிக முக்கிய முடிவு மதிப்பெண்ணை கட்டுப்படுத்தும்.')}</p></div>
      <div className="panel pad rv" style={{ borderRadius: 26 }}><div className="row" style={{ gap: 22, marginBottom: 14 }}><Ring v={82} size={104} /><div><b style={{ fontSize: 18 }}>{L('Verify first', 'முதலில் சரிபார்')}</b><div className="mu">{L('Evidence coverage', 'ஆதார வரம்பு')} <b style={{ color: 'var(--ink)' }}><Num v={45} suf="%" /></b></div></div></div>
        {[[L('Legal', 'சட்டம்'), 90], [L('Revenue & survey', 'வருவாய் & சர்வே'), 62], [L('Neighbourhood', 'சுற்றுப்புறம்'), 80], [L('Planning', 'திட்டமிடல்'), 0]].map(x => <div className="row" key={String(x[0])} style={{ padding: '7px 0' }}><span style={{ width: 130 }}>{x[0]}</span><div className="bar"><i style={{ width: x[1] + '%' }} /></div>{x[1] ? <b className="mono" style={{ width: 40, textAlign: 'right' }}>{x[1]}</b> : <span className="tag a">{L('not checked', 'சரிபார்க்கவில்லை')}</span>}</div>)}</div>
    </div></section>

    <section className="sec dark"><Contours /><div className="pub-in g c2" style={{ alignItems: 'center', gap: 50, position: 'relative' }}>
      <div className="rv"><h2>{L('Take the report with you', 'அறிக்கையை உங்களுடன் எடுத்துச் செல்லுங்கள்')}</h2><p className="lead">{L('A bilingual A4 PDF with the score, highlights, map, findings, ownership chain and the questions to put to the seller. Share it by link or QR.', 'மதிப்பெண், முக்கிய அம்சங்கள், வரைபடம், முடிவுகள், உரிமை சங்கிலி, விற்பவருக்கான கேள்விகளுடன் இருமொழி A4 PDF. இணைப்பு / QR மூலம் பகிரலாம்.')}</p><div style={{ marginTop: 26 }}><Link className="btn lg" style={{ background: '#fff', color: '#0B3B2B', borderColor: '#fff' }} to="/sample">{L('See a sample report', 'மாதிரி அறிக்கையை பார்')}<Arr /></Link></div></div>
      <div className="rv" style={{ perspective: 900 }}><div style={{ background: '#fff', color: '#16201B', borderRadius: 18, padding: 22, transform: 'rotateY(-10deg) rotateX(4deg) rotate(-2deg)', boxShadow: '0 40px 70px -20px rgba(0,0,0,.5)' }}><div className="mono" style={{ color: '#0E7A55' }}>LandAudit</div><b style={{ fontSize: 20, letterSpacing: '-.03em' }}>{L('Property Audit Report', 'நில தணிக்கை அறிக்கை')}</b><div className="row" style={{ marginTop: 12 }}><Ring v={82} size={84} /><div className="sm" style={{ flex: 1 }}>{[L('Legal status', 'சட்ட நிலை'), L('Physical condition', 'நில நிலை'), L('Location', 'இடம்')].map((x, i) => <div key={x} className="row" style={{ justifyContent: 'space-between', padding: '4px 0', borderBottom: '1px solid #EEF0EA' }}><span>{x}</span><b style={{ color: i === 1 ? '#9A6A0C' : '#0E7A55' }}>{[L('Clear', 'தெளிவு'), L('Minor issues', 'சிறு சிக்கல்'), L('Good', 'நன்று')][i]}</b></div>)}</div></div></div></div>
    </div></section>

    <section className="sec"><div className="pub-in"><h2 className="rv">{L('Pay per audit', 'தணிக்கைக்கு ஏற்ப கட்டணம்')}</h2><p className="lead rv">{L('Your first audit is free. After that, one credit runs one audit, and re-running the same case costs nothing.', 'முதல் தணிக்கை இலவசம். பின்னர் 1 கிரெடிட் = 1 தணிக்கை; அதே வழக்கை மீண்டும் இயக்குவது இலவசம்.')}</p><div className="rv" style={{ marginTop: 36 }}><PriceCards /></div></div></section>

    <section className="sec" style={{ paddingTop: 0 }}><div className="pub-in faq" style={{ maxWidth: 820 }}><h2 className="rv" style={{ marginBottom: 14 }}>{L('Questions buyers ask', 'வாங்குபவர்கள் கேட்பவை')}</h2><div className="rv">{faq.map(f => <Faq key={f[0]} q={f[0]} a={f[1]} />)}</div></div></section>

    <section className="pub-in rv" style={{ textAlign: 'center' }}><h2 style={{ fontSize: 44, letterSpacing: '-.045em', marginBottom: 20 }}>{L('Know what the records say before the advance.', 'முன்பணத்துக்கு முன் பதிவுகள் என்ன சொல்கின்றன என்று அறியுங்கள்.')}</h2><Link className="btn lg" to="/register">{L('Start your free audit', 'இலவச தணிக்கையை தொடங்கு')}<Arr /></Link></section>
  </div>;
}