import { Link, useParams } from 'react-router-dom';
import { useL } from '../i18n';
import { useStore } from '../store';
import { analyze } from '../engine';
import { seed } from '../seed';
import { Empty, Tag, inr } from '../ui';
import { Report } from './Case';
import type { Case } from '../types';

export function PriceCards() {
  const { L } = useL();
  const p = [
    { n: L('Single audit', 'ஒரு தணிக்கை'), c: 1, a: 499, d: L('One plot you are about to buy.', 'வாங்கப்போகும் ஒரு நிலம்.') },
    { n: L('Buyer pack', 'வாங்குபவர் பேக்'), c: 5, a: 1999, d: L('Compare several plots, or a family purchase.', 'பல நிலங்களை ஒப்பிட, குடும்ப கொள்முதல்.') },
    { n: L('Advisor pack', 'ஆலோசகர் பேக்'), c: 25, a: 7499, d: L('Brokers, advocates and consultants.', 'தரகர், வழக்கறிஞர், ஆலோசகர்.'), best: true },
  ];
  const inc = [L('Cross-document checks', 'ஆவண ஒப்பீடு'), L('Findings with evidence', 'ஆதாரத்துடன் முடிவுகள்'), L('Bilingual report', 'இருமொழி அறிக்கை'), L('Seller question list', 'விற்பவருக்கான கேள்விகள்')];
  return <div className="g c3">{p.map(x => <div key={x.n} className={`price ${x.best ? 'best' : ''}`}>
    <div className="row"><h3 className="sp">{x.n}</h3>{x.best && <Tag>{L('Lowest per audit', 'குறைந்த விலை')}</Tag>}</div>
    <div className="amt">{inr(x.a)}</div><div className="mu sm">{x.c} {L('audit', 'தணிக்கை')}{x.c > 1 ? 's' : ''} · {inr(Math.round(x.a / x.c))} {L('each', 'ஒன்றுக்கு')}</div>
    <p style={{ margin: '12px 0 0', color: '#46544C' }}>{x.d}</p><ul>{inc.map(i => <li key={i}>{i}</li>)}</ul>
    <Link className={`btn ${x.best ? 'gr' : 'o'}`} style={{ width: '100%' }} to="/register">{L('Start free, buy later', 'இலவசமாக தொடங்கு')}</Link></div>)}</div>;
}

export function Pricing() {
  const { L } = useL();
  return <div className="pub-in" style={{ padding: '64px 24px 80px' }}>
    <h1 className="serif" style={{ fontSize: 40, marginBottom: 8 }}>{L('Simple pricing', 'எளிய கட்டணம்')}</h1>
    <p className="lead" style={{ color: '#46544C', fontSize: 17, maxWidth: 600, marginBottom: 34 }}>{L('Every new account gets one free audit. Credits do not expire, and re-running the same case is free.', 'ஒவ்வொரு புதிய கணக்கிற்கும் 1 இலவச தணிக்கை. கிரெடிட் காலாவதியாகாது; அதே வழக்கை மீண்டும் இயக்குவது இலவசம்.')}</p>
    <PriceCards />
    <div className="g c2" style={{ marginTop: 36 }}>
      <div className="price"><h3>{L('Professional review', 'நிபுணர் மதிப்பாய்வு')}</h3><p style={{ color: '#46544C' }}>{L('An advocate, surveyor, planner or valuer reviews your case and adds a signed remark to the report. Quoted per case, shown before you confirm.', 'வழக்கறிஞர், சர்வேயர், திட்ட நிபுணர், மதிப்பீட்டாளர் உங்கள் வழக்கை மதிப்பாய்வு செய்து அறிக்கையில் குறிப்பு சேர்ப்பார். ஒவ்வொரு வழக்குக்கும் மேற்கோள்; உறுதிக்கு முன் காட்டப்படும்.')}</p><Link to="/professionals">{L('See professionals', 'நிபுணர்களை பார்')}</Link></div>
      <div className="price"><h3>{L('Business', 'வணிகம்')}</h3><p style={{ color: '#46544C' }}>{L('Bulk screening, team accounts, API and your own branding on reports, for brokers, developers, banks and NBFCs.', 'மொத்த சரிபார்ப்பு, குழு கணக்கு, API, உங்கள் முத்திரையுடன் அறிக்கை: தரகர், டெவலப்பர், வங்கி, NBFC-க்கு.')}</p><a href="mailto:hello@landaudit.ai">{L('Talk to us', 'எங்களிடம் பேசுங்கள்')}</a></div>
    </div>
  </div>;
}

function sampleCase(): Case {
  const c = seed().cases.find(x => x.id === 'C-1003')!, now = new Date().toISOString();
  c.nearby = { hospital: [{ name: 'Sample Government Hospital', km: 1.7, lat: 0, lng: 0 }], school: [{ name: 'Sample Higher Secondary School', km: 0.8, lat: 0, lng: 0 }], bank: [{ name: 'Sample Cooperative Bank', km: 1.1, lat: 0, lng: 0 }] };
  c.nearbyAt = now; c.claims = [{ id: 'k1', kind: 'distance', target: 'hospital', km: 1, text: 'Hospitals within 1 km' }];
  c.audit = analyze(c); return c;
}
export function Sample() {
  const { L } = useL(), c = sampleCase();
  return <div style={{ background: 'var(--bg)', padding: '30px 0 70px' }}><div className="pub-in">
    <div className="notice">{L('Sample report with illustrative data. Names, numbers and places are made up to show the format.', 'மாதிரி அறிக்கை; பெயர், எண், இடங்கள் வடிவத்தை காட்ட உருவாக்கப்பட்டவை.')}</div><Report c={c} /></div></div>;
}

export function Shared() {
  const { token } = useParams(), s = useStore(), { L } = useL(), c = s.cases.find(x => x.share?.token === token && x.share?.on);
  if (!c) return <div className="pub-in" style={{ padding: 80 }}><Empty title={L('This report link is not available', 'இந்த அறிக்கை இணைப்பு கிடைக்கவில்லை')} hint={L('The owner may have turned sharing off.', 'உரிமையாளர் பகிர்வை நிறுத்தியிருக்கலாம்.')} /></div>;
  return <div style={{ background: 'var(--bg)', padding: '30px 0 70px' }}><div className="pub-in">
    <div className="notice">{L('Shared report', 'பகிரப்பட்ட அறிக்கை')} · ID <b>{c.id}-{token}</b> · {L('Read-only copy generated by LandAudit. Confirm the ID with the person who sent it.', 'LandAudit உருவாக்கிய படிக்க மட்டும் நகல். அனுப்பியவரிடம் ID-ஐ உறுதி செய்யவும்.')}</div><Report c={c} /></div></div>;
}

const DOCS: Record<string, { t: [string, string]; body: [string, string][] }> = {
  terms: { t: ['Terms of use', 'பயன்பாட்டு விதிகள்'], body: [
    ['What the service is', 'LandAudit helps you review land documents and public map data before a purchase. It produces a report of matches, mismatches and unchecked items.'],
    ['What it is not', 'It is not legal advice, a title opinion, a survey or a valuation. Do not rely on it as a substitute for an advocate or a licensed surveyor.'],
    ['Your documents', 'You confirm you have the right to upload the documents. You are responsible for the accuracy of values you confirm or edit.'],
    ['Credits and refunds', 'Credits run audits. A completed audit is not refundable. A failed audit that did not produce a report is credited back.'],
    ['Changes', 'We may update these terms. Material changes are shown in the app before they apply.'] ] },
  privacy: { t: ['Privacy', 'தனியுரிமை'], body: [
    ['What we collect', 'Your name, email and mobile number, the property details you enter, the documents you upload and the values extracted from them.'],
    ['Why', 'To run your audit, produce your report and keep your account secure. We do not sell your data.'],
    ['Sharing', 'A report is private to you. It becomes visible to others only when you turn on a share link, and you can turn it off at any time. Professionals see a case only after you request their review.'],
    ['Your control', 'You can edit your profile, and delete your account with every case and document from Settings.'],
    ['Third parties', 'Map tiles and nearby places come from OpenStreetMap and Esri services, which receive map requests from your browser.'] ] },
  disclaimer: { t: ['Disclaimer', 'பொறுப்புத் துறப்பு'], body: [
    ['Due-diligence aid', 'Findings depend on the documents you provide, the values you confirm and the data sources available. Items marked “Not verified” have no reliable source behind them.'],
    ['No certification', 'A high score does not mean a title is clean, and a low score does not mean the land is illegal. Mismatches are things to verify with the competent authority, an advocate or a surveyor.'],
    ['Map data', 'Distances are straight-line from your pin and come from community-maintained data that may be incomplete.'] ] },
};
export function Legal() {
  const { doc } = useParams(), { L, lang } = useL(), d = DOCS[doc ?? ''];
  if (!d) return <div className="pgl"><Empty title="Not found" /></div>;
  return <div className="pgl"><h1>{lang === 'ta' ? d.t[1] : d.t[0]}</h1>
    <div className="notice" style={{ marginTop: 14 }}>{L('Draft text. Have a lawyer review it before launch.', 'வரைவு உரை. தொடங்கும் முன் வழக்கறிஞரிடம் மதிப்பாய்வு செய்யவும்.')}</div>
    {d.body.map(([h, p]) => <div key={h}><h2>{h}</h2><p>{p}</p></div>)}</div>;
}
